- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
- app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/layout/fragment_following.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/values/strings.xml
- 메인에 들어갈 Fragment 추가
- 패키지 구조 만듦
> #2 [CHORE] : Add fragments and packaging

- app/build.gradle
- app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- ViewPager2/BottomNav 어댑터 만들고 연결
> #5 [FEAT] : Make Adapter for Bottom Nav/ViewPager2

- app/src/main/java/com/teambeme/beme/base/BindingActivity.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
> #4 [FEAT] : Make BindingActivity

- app/src/main/java/com/teambeme/beme/base/BindingActivity.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
- Base 클래스 만듬(Binding Activity)
> Merge l2hyunwoo to Develop

- app/build.gradle
- app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
- app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
- app/src/main/res/drawable/ic_alarm.xml
- app/src/main/res/drawable/ic_plus_follower.xml
- app/src/main/res/layout/fragment_explore.xml
> #24 [STYLE] : Make Explore Fragment UI

- app/src/main/res/drawable/explore_otherminds_content_shape.xml
- app/src/main/res/drawable/explore_otherminds_title_shape.xml
- app/src/main/res/drawable/ic_showdetail.xml
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/layout/list_explore_otherminds.xml
> #33 [STYLE] : Make RecyclerView otherminds from Explore

- app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
- app/src/main/java/com/teambeme/beme/util/NestedScrollableHost.kt
- app/src/main/res/layout/fragment_home.xml
add NestedScrollableHost.kt because of nested viewpager2 issue
> #52 [FEAT] : Add ViewModel, set data function

- app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
Fix missing } in ExploreFragment.kt
> Yjooooo explore

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teambeme/beme/MyFirebaseMessagingService.kt
- app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
- app/src/main/java/com/teambeme/beme/notification/NotificationActivity.kt
- app/src/main/java/com/teambeme/beme/notification/adapter/BackQuestionAdapter.kt
- app/src/main/res/values/strings.xml
새 브랜치(semin_push_alarm) 파서 이전 브랜치(semin_alarm)의 변경사항들을 옮김
> [CHORE] : 푸시 알림 구현관련 풀리퀘 문제로 다시 새 브랜치 파서 작업

- README.md
- app/build.gradle
> Merge l2hyunwoo_docs to develop

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teambeme/beme/BeMeApplication.kt
- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
- app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
- app/src/main/java/com/teambeme/beme/util/DisplayUtil.kt
- app/src/main/res/layout/activity_answer.xml
- 툴바 UI 기능 구현
- Footer 스위치 기능 구현
issue track: #154 #155
> [FEAT] : AnswerActivity.kt modify

- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- ApplicationContext를 가져올 수 없었던 문제 해결
> AnswerViewModel error fixed

- app/src/main/java/com/teambeme/beme/data/remote/api/LoginService.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
- app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
- app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
- app/src/main/java/com/teambeme/beme/util/ErrorBody.kt
- app/src/main/res/layout/activity_login.xml
- 로그인 뷰 에러바디 파싱해서 에러처리
- 홈 뷰 MyPageFragment.kt 뷰페이저 어댑터 수정해서 에러 수정
issue track: #284, #285
> [FIX] : 로그인 뷰, 홈 뷰 원상 복구

- .idea/codeStyles/Project.xml
- app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
- app/src/main/res/layout/item_following_after_idsearch.xml
> [FEAT] : 아이디 검색에서 팔로우 와 팔로잉 기능 구현

- .idea/codeStyles/Project.xml
- app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
- app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
- app/src/main/res/layout/activity_notification.xml
> Semin ontime push

- app/src/main/java/com/teambeme/beme/BeMeApplication.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
- app/src/main/java/com/teambeme/beme/main/repository/MainRepositoryImpl.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
> [FIX] : 파이어베이스 토큰 부분 수정 메인페이지로 옮김

- app/src/main/res/drawable/btn_notification_to_see_more_background.xml
- app/src/main/res/layout/activity_notification.xml
> [FIX] : 노티피케이션 뷰 더보기 버튼 줄이기

- .idea/codeStyles/Project.xml
- app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/following/adapter/FollowingProfilesRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/following/adapter/SearchProfilesRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/following/view/FollowingShowAllActivity.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
- app/src/main/res/layout/item_explore_other_minds.xml
- app/src/main/res/layout/item_following_after_idsearch.xml
- Explore : 나와 다른 생각들 레이아웃 수정하기
- Following : 답변하고 확인하기가 나오는 글 카드 눌렀을 때, 상세보기로 이동 막기
- FollowingIdSearch : 검색결과 없을 시 띄우는 글 버그 수정
- FollowingIdSearch : 자기아이디 검색 -> 검색결과없음 띄우기
- FollowingIdSearch : 재검색 시 전 검색 기록 안남게 수정
- FollowingIdSearch : 아이디 검색했을 때 팔로잉, 팔로우 버튼 항상 팔로우로 뜨는 것 수정
issue track : #447, #448, #449, #450, #451, #452
> [Fix] Fix Bug in Explore, FollowingIdSearch, Following

- app/src/main/res/layout/activity_following_after_id_search.xml
- app/src/main/res/layout/activity_following_show_all.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_notification.xml
- app/src/main/res/layout/activity_other_page.xml
- app/src/main/res/layout/activity_sign_up.xml
- app/src/main/res/layout/fragment_explore.xml
- app/src/main/res/layout/fragment_my_scrap.xml
- app/src/main/res/layout/fragment_my_write.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- 다크모드 배경 이슈 해결
- 서치뷰 : 서치 아이콘, 높이 수정 (스타일 적용)
issue track : #454, #456
> Fix Bug when we use Dark Mode

- app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/res/layout/item_home_more_question.xml
- 날짜 포매팅
- 과거의 질문 더 보기 부분 수정
issue track: #482, #483
> [FIX] : Answer 관련 오류 수정

- app/release/output-metadata.json
- app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
- app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
- app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
- app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
> [FIX] : Base URL 수정 및 에러 수정

- app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
> Home 페이징 오류 수정/Explore 날짜 포매팅 오류 수정

- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
- 홈 수정 버튼 누를 시 수정여부 반영 안되는 에러 해결
- 글쓰기 버튼 후 Refresh가 안되던 문제 해결
issue track: #505, #506
> [FIX] : Home, 글쓰기 부분 에러 해결

- app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
- app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
- app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
- app/src/main/res/drawable/switch_thumb.xml
- app/src/main/res/layout/item_explore_other_questions.xml
Following : 답변하지 않은 질문 카드 디자인 수정
issue track : #533
> Fix Answer Card Design at FollowingFragment.

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
- app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
- app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
- app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
- app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
- app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/main/model/ScreenName.kt
- app/src/main/java/com/teambeme/beme/mypage/model/CategoryFilter.kt
- app/src/main/java/com/teambeme/beme/mypage/model/PublicRange.kt
- app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
- app/src/main/java/com/teambeme/beme/notification/adapter/NoticeAdapter.kt
- app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
- app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
- app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
- app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
- app/src/main/java/com/teambeme/beme/signup/view/TermFragment.kt
- app/src/main/java/com/teambeme/beme/util/FirebaseEventUtil.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/fragment_my_write.xml
> Merge l2hyunwoo develop

- app/src/main/res/layout/activity_detail.xml
- app/src/main/res/values/colors.xml
- Detail : 댓글 입력창 레이아웃 margin 안 맞는 것 수정
- Detail : 전체 뷰 레이아웃 margin 안 맞는 것 수정
issue track : #597, #598
> [STYLE] : Modify Layout Margin.

- .idea/sonarIssues.xml
- README.md
- app/build.gradle
- app/src/main/java/com/teambeme/beme/BeMeApplication.kt
- app/src/main/java/com/teambeme/beme/data/local/singleton/BeMeRepository.kt
- app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
- app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
- app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
- app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
- app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
- app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
- app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
- app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModel.kt
- app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
- app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
- app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
- build.gradle
> 질문 수정 1일 1회 제한 기능 구현

- .idea/sonarIssues.xml
- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- app/src/main/res/layout/activity_answer.xml
> UI 고쳐야할 부분 고침

- app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
- app/src/main/res/layout/activity_answer.xml
- Answer : 키보드 올라왔을 때 EditText Bottom margin 변경
- Answer : 빈 화면 클릭하면 키보드 숨기기
issue track : #656, #657
> [FEAT] 키보드 관련 이슈 해결

- app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
- app/src/main/java/com/teambeme/beme/mypage/model/CategoryFilter.kt
- app/src/main/java/com/teambeme/beme/mypage/model/PublicRange.kt
- app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
- app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
- app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
- app/src/main/res/layout/fragment_my_scrap.xml
- app/src/main/res/layout/fragment_my_write.xml
- 내글 : 더보기 유지
- 내스크랩 : 더보기 유지
- 필터링 : 같은 카테고리 두번 클릭시 비정상 종료 해결
- 필터링 : 카테고리 선택하다 모두 선택해제 하고 적용하기를 눌렀을 경우 이전 선택한 필터링이 적용되는 문제 해결
> MyPage 관련 이슈들 해결

- .idea/sonarIssues.xml
- app/build.gradle
- versionCode -> 10
- versionName -> "1.1.3"
> [CHORE] : Version change
